name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 4320
    steps:
    - name: Download MegaSync
      run: Invoke-WebRequest https://mega.nz/MEGAcmdSetup.exe -OutFile MEGAcmdSetup.exe
    - name: Install MegaSync
      run: Start-Process "MEGAcmdSetup.exe" -ArgumentList "/S"
    - name: SyncON
      env:
          MEGA_LOGIN: ${{ secrets.MEGA_LOGIN }}
          MEGA_PASS: ${{ secrets.MEGA_PASS }}
      run: Start-Process "$env:LOCALAPPDATA\MEGAcmd\mega-login" -ArgumentList "${MEGA_LOGIN} ${MEGA_PASS}"; Start-Process "$env:LOCALAPPDATA\MEGAcmd\mega-sync" -ArgumentList  "$env:USERPROFILE\Desktop RDP_DESKTOP"
      shell: powershell
      
    - name: Download NGrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract NGrok
      run: Expand-Archive ngrok.zip
    - name: Auth NGrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
